name: Deploy to GitHub Pages

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Setup Pages
        uses: actions/configure-pages@v4
        with:
          static_site_generator: next
          
      - name: Build with Next.js
        run: npm run build
        env:
          NODE_ENV: production
          GITHUB_PAGES: true
          
      - name: Create deployment directory
        run: |
          mkdir -p deploy
          if [ -d "dist" ]; then
            cp -r dist/* deploy/
          elif [ -d "out" ]; then
            cp -r out/* deploy/
          elif [ -d ".next" ]; then
            cp -r .next/static deploy/static
            cp -r public/* deploy/ 2>/dev/null || true
          else
            echo "No build output found, creating basic index"
            echo "<h1>Build output not found</h1>" > deploy/index.html
          fi
          echo "Deploy directory contents:"
          ls -la deploy/
          
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: deploy

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4